"""
SentinelX AI – Endpoint Agent Schemas
Pydantic data models for agent enrollment, heartbeat, telemetry ingestion, listing, and health stats.
"""

from uuid import UUID
from datetime import datetime, timezone
from typing import Any, List, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field


# ── Enrollment Schemas ───────────────────────────────────────────────────

class AgentEnrollRequest(BaseModel):
    """Payload sent by the endpoint agent when enrolling for the first time."""

    agent_id: str = Field(..., description="Unique UUID string generated by the installation")
    hostname: str = Field(..., min_length=1, max_length=255, description="Endpoint hostname")
    platform: str = Field(default="Windows", max_length=100, description="Operating system platform")
    os_version: Optional[str] = Field(default=None, max_length=255, description="Detailed OS version string")
    agent_version: str = Field(default="1.0.0", max_length=50, description="Installed agent version")
    local_ip: Optional[str] = Field(default=None, max_length=45, description="Local network IP address")
    architecture: Optional[str] = Field(default=None, max_length=50, description="CPU architecture (e.g., x86_64, AMD64)")
    username: Optional[str] = Field(default=None, max_length=255, description="Primary user logged into endpoint")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional endpoint metadata")

    model_config = ConfigDict(from_attributes=True)


class AgentEnrollResponse(BaseModel):
    """Response returned upon successful agent enrollment."""

    id: UUID = Field(..., description="Database internal UUID for the agent")
    agent_id: str = Field(..., description="Unique installation UUID string")
    hostname: str = Field(..., description="Hostname of the enrolled endpoint")
    platform: str = Field(..., description="Platform")
    os_version: Optional[str] = Field(None, description="OS version")
    agent_version: str = Field(..., description="Agent software version")
    status: str = Field(..., description="Enrollment status (e.g. Online)")
    enrolled_at: datetime = Field(..., description="Enrollment timestamp")
    agent_token: str = Field(..., description="Short-lived / secure agent authentication token")
    token_type: str = Field(default="Bearer", description="Token type prefix")

    model_config = ConfigDict(from_attributes=True)


# ── Heartbeat Schemas ────────────────────────────────────────────────────

class AgentHeartbeatRequest(BaseModel):
    """Periodic status payload sent by the agent."""

    agent_id: str = Field(..., description="Unique installation agent UUID")
    hostname: str = Field(..., description="Endpoint hostname")
    agent_version: str = Field(default="1.0.0", description="Agent software version")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Agent timestamp")
    uptime: int = Field(default=0, ge=0, description="Agent or system uptime in seconds")
    health_status: str = Field(default="Healthy", description="Internal agent health status ('Healthy', 'Degraded', 'Error')")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Updated health metrics or runtime data")

    model_config = ConfigDict(from_attributes=True)


class AgentHeartbeatResponse(BaseModel):
    """Response returned after processing a heartbeat."""

    agent_id: str = Field(..., description="Agent UUID string")
    status: str = Field(..., description="Updated calculated status ('Online', 'Stale', 'Offline', 'Disabled', 'Revoked')")
    last_seen: datetime = Field(..., description="Server last_seen timestamp")
    next_heartbeat_seconds: int = Field(default=60, description="Recommended interval until next heartbeat")

    model_config = ConfigDict(from_attributes=True)


# ── Telemetry Ingestion Schemas ─────────────────────────────────────────

class AgentTelemetryCreate(BaseModel):
    """Single telemetry event record payload."""

    agent_id: Optional[str] = Field(None, description="Agent UUID string (optional if bound in batch header)")
    event_type: str = Field(..., min_length=1, max_length=100, description="Event classification (e.g., 'windows_event', 'process', 'network', 'system')")
    event_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp")
    severity: str = Field(default="INFO", description="Log level/severity (TRACE, DEBUG, INFO, WARNING, ERROR, CRITICAL)")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Structured event payload")
    source: Optional[str] = Field(default="Endpoint Agent", max_length=100, description="Event source identifier")
    is_simulated: bool = Field(default=False, description="Flag explicitly indicating if event was generated in test mode")

    model_config = ConfigDict(from_attributes=True)


class AgentTelemetryBatchCreate(BaseModel):
    """Batch container for ingesting multiple telemetry items in one HTTP call."""

    agent_id: str = Field(..., description="Agent UUID string")
    telemetry: List[AgentTelemetryCreate] = Field(..., min_length=1, max_length=1000, description="List of telemetry events")

    model_config = ConfigDict(from_attributes=True)


class AgentTelemetryResponse(BaseModel):
    """Formatted telemetry response model."""

    id: UUID
    agent_id: UUID
    event_type: str
    event_timestamp: datetime
    severity: str
    payload: Dict[str, Any]
    source: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AgentTelemetryListResponse(BaseModel):
    """Paginated list of telemetry records."""

    total: int
    page: int
    page_size: int
    items: List[AgentTelemetryResponse]

    model_config = ConfigDict(from_attributes=True)


# ── Endpoint Agent Management Schemas ─────────────────────────────────────

class EndpointAgentSummary(BaseModel):
    """Summary view for endpoint table rows in frontend UI."""

    id: UUID
    agent_id: str
    hostname: str
    platform: str
    os_version: Optional[str] = None
    agent_version: str
    status: str
    enrolled_at: datetime
    last_seen: Optional[datetime] = None
    local_ip: Optional[str] = None
    risk_score: float = 0.0
    telemetry_count: int = 0

    model_config = ConfigDict(from_attributes=True)


class EndpointAgentResponse(BaseModel):
    """Detailed model representation of an enrolled agent."""

    id: UUID
    agent_id: str
    hostname: str
    platform: str
    os_version: Optional[str] = None
    agent_version: str
    status: str
    enrolled_at: datetime
    last_seen: Optional[datetime] = None
    agent_metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class EndpointAgentListResponse(BaseModel):
    """Paginated list of endpoint agents."""

    total: int
    page: int
    page_size: int
    items: List[EndpointAgentSummary]

    model_config = ConfigDict(from_attributes=True)


class EndpointAgentStatsResponse(BaseModel):
    """Dashboard metrics for live endpoint health."""

    total_endpoints: int = 0
    online_endpoints: int = 0
    offline_endpoints: int = 0
    stale_endpoints: int = 0
    telemetry_events_today: int = 0
    endpoint_threats: int = 0
    highest_risk_endpoint: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class EndpointDetailsResponse(BaseModel):
    """Comprehensive details view payload for a specific endpoint."""

    agent: EndpointAgentResponse
    system_info: Dict[str, Any]
    agent_health: Dict[str, Any]
    last_heartbeat: Optional[datetime] = None
    recent_telemetry: List[AgentTelemetryResponse] = Field(default_factory=list)
    recent_security_events: List[Dict[str, Any]] = Field(default_factory=list)
    recent_threats: List[Dict[str, Any]] = Field(default_factory=list)
    risk_score: float = 0.0
    network_connections: List[Dict[str, Any]] = Field(default_factory=list)
    running_processes: List[Dict[str, Any]] = Field(default_factory=list)
    timeline: List[Dict[str, Any]] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)
